[package]
name = "ts"
version.workspace = true
edition.workspace = true

[dependencies]
byteorder.workspace = true

[features]
default = ["proto-ipv4", "proto-ipv6"]

"proto-ipv4" = []
"proto-ipv6" = []
